[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_STYTCH_PUBLIC_TOKEN"

[[plugins]]
  package = "@netlify/plugin-nextjs" 